remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: [HACKTOBERFEST GYE 2024]
description: [Information and contribution page]
